### ISSUE TITLE
Raspberry Pi os - 64bit - System.DllNotFoundException: Unable to load shared library...

### ISSUE THREAD

**Issue by Matthew-Collins** [johannesegger/SenseHatNet#6] opened 2020-06-04 18:40 UTC
Hi,

Just tried your library on the very new (beta) 64bit Raspberry Pi OS... and got this:

Unhandled exception. System.DLLNotFoundException: Unable to load shared library 'libRTIMULibWrapper.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_Debug environment variable: liblibTRIMULibWrapper.so: cannot open shared object file: no such file or directory
  at Sense.NativeMethods.RTIMUSettings_createDefault()
  at Sense.RTIMU.RTIMUSettings.createDefaults()
  at ....

Can it be re-compiled for 64 bit ?

Thanks
Matt

**Comment by johannesegger** [comment] 2020-06-05 06:21
Thanks for reporting.
I tried to use a different compiler in the [build image](https://github.com/johannesegger/SenseHatNet/blob/master/RTIMULib-dev/Dockerfile) without success. I'm not sure what needs to be changed to compile for 64 bit. Is it also the docker image or only the compiler? Everything else should be simple as soon as it compiles.

**Comment by johannesegger** [comment] 2020-06-05 07:16
I simply [changed](https://github.com/johannesegger/SenseHatNet/commit/0d305c98f7c8424f06fd1dd7b9695909990bdbc0) the compile target to armv8 and published a [prerelase version](https://www.nuget.org/packages/SenseHatNet/0.0.6-armv8). Could you try that and report back?

**Comment by johannesegger** [comment] 2020-06-05 07:28
I published another [version](https://www.nuget.org/packages/SenseHatNet/0.0.6-armv8-mcpu) that uses `-mcpu` instead of `-march` when compiling (see f4d69356d98521c13574797eb06abba12053095d). Please also try that.

**Comment by Matthew-Collins** [comment] 2020-06-05 12:46
Same error on both those... please try...

**Comment by johannesegger** [comment] 2020-06-06 11:57
Last try before I probably give up: Can you please try [0.0.6-linaro-x64](https://www.nuget.org/packages/SenseHatNet/0.0.6-linaro-x64) (see e86b162)?

**Comment by Matthew-Collins** [comment] 2020-06-11 13:03
Apologies for the delay in getting back.....  it has the same error... tried on a couple of sd cards and pi's

Is aarch64 an option ?

Do you have the hardware to re-produce ?

**Comment by johannesegger** [comment] 2020-06-11 17:56
No, I don't have the hardware, unfortunately. That's why I'm just guessing...
Could you try forcing 32 bit in your .csproj file as a workaround?

```xml
<PropertyGroup>
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>
```

or in Visual Studio

![image](https://user-images.githubusercontent.com/237707/84422389-3b787300-ac1d-11ea-9bc3-544b41d598da.png)
(stolen from https://www.neovolve.com/2015/07/31/disable-prefer-32-bit/)

The latest version has got something to do with aarch64, but I'm not sure at all.

**Comment by AngeloBestetti** [comment] 2020-10-29 20:07
Same here....using Raspi4 x64

**Comment by johannesegger** [comment] 2020-10-30 09:09
I still don't have the hardware, sorry. But I always accept PRs ;-)

**Comment by johannesegger** [comment] 2020-11-01 11:59
I gave it another try and published [0.0.6-arm32-aarch64-0001](https://www.nuget.org/packages/SenseHatNet/0.0.6-arm32-aarch64-0001). Can you guys please try that?  
I also ordered a Pi 4 so I'll soon be able to try it as well.

**Comment by AngeloBestetti** [comment] 2020-11-01 15:53
> I gave it another try and published [0.0.6-arm32-aarch64-0001](https://www.nuget.org/packages/SenseHatNet/0.0.6-arm32-aarch64-0001). Can you guys please try that?
> I also ordered a Pi 4 so I'll soon be able to try it as well.

I will do the test, just reinstalling 64bits version here.

**Comment by AngeloBestetti** [comment] 2020-11-01 17:13
On all my tests I´m getting this message:
System.DllNotFoundException: 'Unable to load shared library 'libRTIMULibWrapper.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibRTIMULibWrapper.so: cannot open shared object file: No such file or directory'

For some reason it´s not finding libRTIMULibWrapper.so, but I enabled LD_DEBUG=libs and it is looking in the correct folder.

**Comment by johannesegger** [comment] 2020-11-01 21:55
What folder does it look in? With `0.0.6-arm32-aarch64-0001` there are two versions of `libRTIMULibWrapper.so`, one for ARM and one for AArch64. `DllNotFoundException` could also mean that it looked in the wrong folder.

**Comment by Matthew-Collins** [comment] 2020-11-02 18:32
Hi,

YES it works on 64bit and 32bit !!

Try Nuget package: Tick: Show Prerelease:
0.0.6-arm32-aarch64-0001

Thanks
Matt

**Comment by johannesegger** [comment] 2020-11-03 05:04
That's great to hear, thank you for taking the time to try all those different versions and sorry that it took so long. @AngeloBestetti can you confirm that it works with `0.0.6-arm32-aarch64-0001`?

**Comment by AngeloBestetti** [comment] 2020-11-03 19:51
My applications does not look into bin/Debug/netcoreapp3.1/runtimes/linux-arm[linux-arm64]

So I decided to copy to /usr/local/lib and it works (more or less), now I´m gettings: SPI read error from 162 - Failed to read MS5611 calibration data

But it´s ok, on 32bits works fine, just 64bits it´s doing that, thank you very much.

**Comment by johannesegger** [comment] 2020-11-04 08:12
Thanks for trying it out. I think I have to wait for my Pi to debug that myself.

**Comment by johannesegger** [comment] 2020-11-06 08:29
I spent some more time on this, but I can only say that native libraries suck: The cross compiler `aarch64-linux-gnu-g++` produces different results on different environments (Docker, Raspberry Pi OS). When compiling in Docker (debian:10) on my dev machine the resulting library and sample app works in a docker container on my Pi, but not natively on the Pi. When compiling on the Pi it works on the Pi, but not in a docker container on the Pi. So to summarize: I'm lost on 64 bit.

**Comment by AngeloBestetti** [comment] 2020-11-06 10:48
That's ok we all are deve developers, we know how hard it is. Thank you
any way.

Em sex, 6 de nov de 2020 05:30, Johannes Egger <notifications@github.com>
escreveu:

**Comment by johannesegger** [comment] 2020-11-07 13:24
@AngeloBestetti for the new errors you get: Try deleting RTIMULib.ini and enable SPI and I2C using raspi-config.

**Comment by johannesegger** [comment] 2020-11-07 13:56
After one more day I think it finally works on 32 bit docker/native and 64 bit docker/native. Please try v0.0.6.

**Comment by Matthew-Collins** [comment] 2020-11-07 22:10
Works on 0.0.6: but not if I remove the `<RuntimeIdentifier>linux-arm64</RuntimeIdentifier>` from the proj file, it fails to find libRTIMULib.so.7 ?  

This works on 0.0.6-arm32-aarch64-0001 ?

Can you add a .net5 SenseTest ?

**Comment by johannesegger** [comment] 2020-11-08 12:24
You're right. That's weird. I merged the native libraries into a single one and this seems to make loading it easier. Please try 0.0.7. This one is netstandard2.0 again.
What do you mean with .net5 SenseTest? Do you mean a .NET 5 version of SenseHatNet? Or a sample application with .NET 5?

**Comment by Matthew-Collins** [comment] 2020-11-08 17:19
0.0.7 works great on 32 bit and 64 bit.  :-)

Just your Sample/SenseTest app in .NET 5 (out this Tuesday 10 Nov 2020) ?

**Comment by johannesegger** [comment] 2020-11-08 20:49
I'll install .NET 5 soon, then I can update it.

Please close the issue if it's (finally) resolved.

**Comment by Matthew-Collins** [comment] 2020-11-08 22:37
@AngeloBestetti give v0.0.7 a try ?

**Comment by johannesegger** [comment] 2020-11-12 07:08
The sample now uses .NET 5.

**Closed as completed** 2020-11-12 07:08 UTC

**Comment by mmckechney** [comment] 2020-12-03 22:11
@johannesegger  - I am getting the same error, but on a 32 bit PI. any suggestions?
My app it .NET 5

**Comment by johannesegger** [comment] 2020-12-04 05:57
Did you try the [sample app](https://github.com/johannesegger/SenseHatNet/tree/master/Sample)? Are you running it inside a container?

**Comment by mmckechney** [comment] 2020-12-04 13:15
I did try the sample app, it gave the same "Unable to load shared library 'libRTIMUExt.so'" error. I am not running in a container.

**Comment by johannesegger** [comment] 2020-12-05 12:18
Can't reproduce. What Pi are you using? Which OS? I tried with *Pi 4* and *Raspbian GNU/Linux 10 (buster)*.

**Comment by mmckechney** [comment] 2020-12-07 16:40
I'm using Raspbian GNU/Linux 9 (stretch) on a Pi 3. 
I do have a Pi 4 I can try on and probably worth updating my OS too :-)
Until then, I'll use v4 and .NET core 2.2 which has been working.

**Comment by johannesegger** [comment] 2020-12-07 17:13
`libRTIMUExt` is built in a debian 10 docker container (see [Dockerfile](https://github.com/johannesegger/SenseHatNet/blob/master/RTIMUExt/Dockerfile)), do you think this could be the reason?
I also tried with debian 10 on a Pi 3 which worked, can you verify that?
